FROM node:18.12.0

WORKDIR /app

COPY package.json /app

RUN apt-get update -y && apt-get install -y \
    nano \
    net-tools \
    libasound2 libnss3 libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

# install the lib/dependencies
RUN npm install -g pnpm
RUN pnpm install

COPY . /app

RUN mv env .env

# Run the container
CMD ["npm", "start"]